"""empty message

Revision ID: 4d9e9dd3feef
Revises: 
Create Date: 2019-03-20 01:23:58.333850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d9e9dd3feef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translation', sa.Column('original_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translation', 'original_count')
    # ### end Alembic commands ###
